toladata/TolaTables

README.md
datasources/commcare/templates/getcommcareforms.html
datasources/commcare/util.py
datasources/commcare/views.py
datasources/fileuploadjson/views.py
silo/api.py
silo/gviews_v4.py
silo/models.py
silo/views.py
templates/display/silo.html
templates/silo/getonaforms.html
tola/urls.py
tola/util.py

Fixed #205
Fixed #210 
Fixed #211 
Fixed #216 
Fixed #215 
Fixed #213
Fixed #214 
Added #219

Fixed issues with importing from ONA and updating data

---

silo/api.py
silo/gviews_v4.py
silo/views.py
templates/base.html
templates/display/export_form.html
templates/display/silos.html
tola/urls.py

This update adds more control over what exactly to export

Dev export options

---

README.md
docker-entrypoint-dev.sh
fixtures/sites.json

Random fixes for the dev setup.

Fix dev setup

---

.drone.yml
.travis.yml
docker-compose-dev.yml
requirements-ci.txt
silo/apps.py
silo/models.py
silo/tests/__init__.py
silo/tests/test_create_customform.py
silo/views.py
tola/settings/base.py
tola/settings/local.py
tola/settings/test.py

Purpose
======
Fixes:
* Mongo dev setup
* Travis builds
* Drone builds
Also uncomments the only test that at the moment works.

MongoDB refactoring and builds

---

Dockerfile
docker/etc/nginx/nginx.conf

Extended the Dockerfile and introduced another nginx reverse proxy to serve static files directly and proxy the wsgi server. Static files will be served while bypassing the wsgi process .

Add another reverse proxy layer esp. for serving static files

---

.drone.yml
.travis.yml
README.md
factories/silo_models.py
silo/models.py
silo/tests/test_views.py
silo/views.py
templates2/index.html
tola/context_processors.py
tola/urls.py
tola/views.py

Purpose
=====
Just some random improvements I want to do.

Small improvements

---

docker-entrypoint-dev.sh

Purpose
=====
Make Dev server startup faster and avoid unnecessary extra steps.

Do not generate migration files on Dev entrypoint

---

silo/tests/test_views.py
silo/views.py

The export functionality wasn't working properly. The users should be able to export data to CSV.

Fix export csv function #363

---

silo/tests/test_views.py
templates2/base.html
tola/models.py
tola/tests/test_views.py
tola/views.py

The user should be able to log out in track and activity at the same time.
Related ticket: #366

Add logout option

---

silo/tests/test_views.py
static/js/app.js
templates2/base.html

Updating the current logout button to a drop-down with the logout option.
@jurzyna needs to update the style and generates a new CSS class for the drop-down.
Related ticket: #366 
Related PR: #374

Update the profile/logout button to dropdown

---

datasources/fileuploadjson/views.py
silo/models.py
silo/tests/test.py
silo/tests/test_views.py
silo/views.py
static/js/app.js
templates2/base.html
tola/auth_pipeline.py
tola/settings/base.py
tola/settings/local-sample.py
tola/settings/test.py
tola/tests/test_oauth.py
tola/urls.py
tola/util.py

- Fix duplicate UUID [#381](https://github.com/toladata/TolaTables/pull/381)
- Fix warnings and deprecations [#376](https://github.com/toladata/TolaTables/pull/376)
- Update the profile/logout button to dropdown [#375](https://github.com/toladata/TolaTables/pull/375)

Dev v2 into Staging

---

silo/gviews_v4.py

Ticket
====
https://github.com/toladata/TolaTables/issues/380

Remove org specific info from GSheet URL #380

---

factories/silo_models.py
silo/tests/test_views.py
silo/views.py
templates2/silo/getonaforms.html

When a user imports a form from ONA, they aren't redirected to the created table. They should be redirected to the created table when the importing is done.
Related ticket: #379

Redirect user to table

---

silo/api.py
silo/serializers.py

We need to filter the some models by uuid for the synchronization.
Related ticket: TolaActivity/[#994](https://github.com/toladata/TolaActivity/issues/994)
Related PR: TolaActivity/[#1005](https://github.com/toladata/TolaActivity/pull/1005)

Sync Project and TolaUser models

---

docker-entrypoint-dev.sh
factories/silo_models.py
silo/tests/test_views.py
silo/views.py
tola/management/commands/loadinitialdata.py
tola/management/commands/tests/test_loadinitialdata.py

Sometimes the fixtures aren't loaded correctly and we needed to improve the way to load demo data as was done in Activity
Add a new django-admin command to load demo data instead.
Related ticket: #391

Add loadinitialdata command

---

.drone.yml

As far as deployment moved to drone.humanitec.io we have to use it.
Deployment moved to drone.humanitec.io
Trigger deployment on drone.humanitec.io

Trigger deployment on Humanitec drone

---

silo/tests/test_views.py
silo/views.py

Deleting a column should delete the data in the column and the column itself.
We were splitting the name of columns with `_` to remove the `_delete` substring, I just removed this part and we remove only the delete substring.
Related ticket: #413

Columns with _ in their name are not deleted

---

silo/tests/test_views.py

The ticket seems to be done in another one, so I just updated some tests and created a test to cover this case.
Related ticket: #417

Edit column keep data

---

silo/api.py
silo/tests/test_customformview.py

The frontend guys updated the form URL.
Related ticket: #398

Update the URL of custom form source

---

silo/api.py
silo/serializers.py
silo/tests/test_customformview.py

The custom form should have its own serializer.
Related ticket: #456

Add a serializer for the CustomForm view set

---

requirements/base.txt

Fix the celery error when uploading CSV files.
Just updates the version of the celery package.
There's an error in the version of celery that we were using but it was fixed in the version `4.1.1`.
This issue was reported here: https://github.com/celery/celery/issues/4747
Related ticket: #501

Fix celery error

---

silo/api.py
silo/serializers.py
silo/tests/test_customformview.py

The CustomForm view set should use the serializer to validate the data.
I'm serializing the request data.
Related ticket: #515

Update the customform viewset

---

silo/tests/test_views.py
templates2/base.html

We need to add the InlineManual Tour tool to Track as we have in Activity.
Related ticket: #524

Add InlineManual Tour tool

---

silo/api.py
silo/tests/test_customformview.py

There's a typo in the name of one of the default form columns. It doesn't raise any error but it produces a table with an empty column.
- Updated the name of the column
- Using the same list of columns to make sure that we're adding data to the right columns
Related ticket: #542

Fix typo in the column name of forms
