toladata/TolaTables

templates/base.html

Tola's brand font, Scandia, is now added to the bottom of the `body` element.
@glind: Can you verify that this app only has the `base.html` layout? Activity had three. Just want to make sure I wasn't missing one. If there are more, point me to them, or copy `templates/base.html#182-184` into additional ones.
This PR also includes a minor HTML syntax fix near the top of `base.html`.
:clap:

Add Web Fonts

---

docker-entrypoint-dev.sh
silo/__init__.py
silo/apps.py
tola/settings/base.py

Purpose
======
Fixes the exception that could not be found in tests:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf …
```

Fix MongoDB connection error

---

docker-compose-dev.yml
templates2/base.html
tola/context_processors.py
tola/settings/base.py
tola/settings/local.py

Purpose
======
This is a first step to fix ticket:
https://github.com/toladata/TolaTables/issues/313
At the moment we have hardcoded variables in the templates, and we need new ones so we can configure them individually for each environment. For compatibility issues with Mercy Corps I can't delete the hardcoded ones.

Enable to import Google API settings from environment variables # 313

---

silo/tests/test_views.py
silo/views.py
templates2/index.html
tola/settings/local.py
tola/settings/test.py

Purpose
======
With the latest PR I skipped a couple of things which I fix in this one.
- Show public silos.
- Use reverse to get the URLs.
- Don't show repeated public silos which belong to the user.
- Changes test settings to use local, so we load the right templates.

Fix missing data in template

---

.travis.yml
factories/silo_models.py
silo/api.py
silo/tests/test_customformview.py
tola/util.py

When a custom form is published, we should be able to collect data with it, in other words, the input data has to be persisted
Related ticket: TolaDataV2/[#611](https://github.com/toladata/TolaDataV2/issues/611)

Add endpoint persist data

---

silo/tests/test_views.py
silo/views.py

A user should be redirected to the login process only if they come from the Activity.
Related ticket: TolaDataV2/[#649](https://github.com/toladata/TolaDataV2/issues/649)
Related PR: TolaActivity/[#895](https://github.com/toladata/TolaActivity/pull/895)

Fix login issue when users come from Activity

---

silo/api.py
silo/tests/test_customformview.py

A Table should be created with "No data available in table"
Related ticket: TolaDataV2/[#794](https://github.com/toladata/TolaDataV2/issues/794)

Fix blank row CustomForm

---

silo/forms.py
silo/tests/sample_data/import_json.json
silo/tests/test.py
silo/tests/test_views.py
silo/views.py
tola/activity_proxy.py
tola/middleware/AjaxMessaging.py
tola/settings/base.py
tola/settings/dev.py

When a user edits a silo, we don't check which programs they're allowed to list. As we currently syncing the programs, we can check which programs on Activity the user has permissions and based on the UUID we show them on Track.
Related ticket:

Check permission based on WorklowTeam

---

tola/middleware/AjaxMessaging.py

When a user is importing a file the import process doesn't end and the page shows the spinner forever.
It was an issue with the `AjaxMessaging` middleware. It inherits the `MiddlewareMixin` now, so it's gonna have the basic functions.
- Do we really need this middleware? It wasn't working until I update the name of the middleware variable.
Related ticket: #405

Fix #405 - Importing data functionatily isn't working properly

---

silo/tests/test_views.py
silo/views.py
templates/display/merge-column-form-inner.html
templates2/display/merge-column-form-inner.html
tola/urls.py

When a user creates a merge table the data sources for that merge table should be listed under the merged table view.
I added the reads from the source tables to the merge table
Related ticket: #146

No Data Sources listed for merged table on Table View

---

tola/auth_pipeline.py
tola/tests/test_oauth.py

When a user uses the social OAuth, the system tries to update or create an organization based on the org from Activity but it fails because it doesn't have the field `oauth_domains`.
I'm creating org data with the used fields instead of using the data from the response and removing the unused fields.
Related ticket: #418

Fix oauth pipeline

---

silo/tests/test_views.py
silo/views.py

When a user mergers two tables they stayed in the merge page but they should be redirected to the new table.
Just added redirect the user to the silo detail page after the merging is done.
Related ticket: #387

Update the do_merge view to redirect the user to silo detail page

---

tola/tests/test_views.py
tola/views.py

When a user logs out from Track, that same user is not being logged out from Activity.
We were sending the user to the Activity API logout but I updated the URL to send it to the application's logout.
Related ticket: #409

Update the Logout URL to log out in Activity too

---

silo/gviews_v4.py
silo/tests/test_gviews_v4.py
templates2/base.html
tola/urls.py

GSheet import is aborted for first-time users
The Google OAuth token wasn't being stored, so I created a view where we pass all the needed info and store them in the db.
Related ticket: #313

GSheet is aborted for first time users

---

silo/views.py

Background import processes get stuck because the related `CeleryTask` object does not exist before creating the task. Apparently the task gets executed faster than the object is save to db.
First create an empty `CeleryTask` object without information for the task in it. Then update it with the `task_id` after the task is created.

Fix issue with CeleryTask not existing when the task is executing

---

silo/api.py
silo/serializers.py
silo/tests/test_siloview.py

The users should be able to see the columns of the table in the silo endpoint. It'll be easier for the name to handle the data afterward.
I only added the columns field to the serializer.
Related ticket: #440

Add columns to the Silo endpoint

---

silo/views.py
templates/display/silo.html

Issues #360 and #305
For #360, removed the truncation of names completely.  If truncated names are needed, a more robust solution will need to be used.
For #305, hid the validation button, because the functionality is not yet working.  Left the javascript code in to allow someone to finish the feature in the future.
@menda may want to review

Small changes for cell edit crashing and type validation

---

tola/tests/test_util.py
tola/util.py

I had to fix the JSON encoder because it was returning a wrong value for the `_id`
Related ticket: #444

Fix JSON encoder

---

silo/api.py
silo/tests/test_siloview.py

Fix the out of range error when fetching table without data.
Related ticket: #449

Fix out of range error in the silo data view

---

silo/gviews_v4.py
silo/management/commands/stripMongoData.py
silo/tests/test.py

Closes #246, values of newly imported data are now stripped of leading and trailing whitespaces before being matched to values in the Mongo DB.
- Stripping of whitespace on data import was implemented in a prior commit.  Without this change,     when header values in the database are compared to newly imported values, they will not match even though they should. This primarily affects tables with unique columns designated and can result in duplicated data in the table.
- Added a management script that strips all whitespace at the begging and end of each value from existing data stored in Mongo DB.  Logging information is printed to STDOUT. 
See above
@Menda 
Related ticket: #246

Closes #246, values of newly imported data are now stripped of whitespaces

---

datasources/commcare/util.py
datasources/commcare/views.py
datasources/fileuploadjson/views.py
factories/silo_models.py
silo/api.py
silo/gviews_v4.py
silo/management/commands/get_all_ona_forms.py
silo/management/commands/get_ona_form_data.py
silo/tasks.py
silo/tests/sample_data/import_json.json
silo/tests/test.py
silo/tests/test_gviews_v4.py
silo/tests/test_siloview.py
silo/tests/test_views.py
silo/views.py
tola/tests/test_util.py
tola/util.py

When a user tries to import data with numbers, the data is saved as strings all the time.
- I had to convert the imported data before saving it into the MongoDB.
- Escape the string before saving the data into the database
Related ticket: #454

The import functionality shouldn't import everything as string

---

silo/tests/test_views.py
silo/views.py
tola/settings/base.py
tola/tests/test_views.py

Preventing unauthorized users to redirect TolaTables login page when they try to access Track and redirect them to Activity login page.
Login url added to settings.
_Related ticket: #466

fix #466 - redirect unauthorized users to activity login page

---

.drone.yml
silo/tests/test_siloview.py

There's a weird error in the `test_data_silo` test and it's related to MongoDB. Currently, we don't know exactly what the problem is. The deletion of documents isn't working properly in the `tearDown` but if we add it to the `setUp` it works as expected.
@leonholub and @bogdangi we should keep tracking this issue and check how to definitely solve it.

Fix the deleting document issue in SiloDataViewTest

---

silo/api.py
silo/permissions.py
silo/tests/test_readview.py
templates2/display/silo.html

Fixes issue #294 "Cannot set table to Auto-Update - fails to finish loading. No error". Since the frontend view is using the API to update the Read and has no tests associated with it i created some tests for the `ReadViewSet`. During testing another issue was discovered and the permissions check was adjusted to correct the error that Read view was requiring missing fields.
_Related ticket: #294_

Fix Read API issue

---

datasources/commcare/views.py
silo/google_views.py
silo/gviews_v4.py
silo/tests/test.py
silo/tests/test_views.py
silo/views.py
templates/display/silo_detail.html
templates/display/silos.html
templates2/display/silo.html
templates2/display/silo_detail.html
templates2/display/silos.html
templates2/index.html
tola/tests/test_views.py
tola/urls.py

Add id column to track table for each row in order to make identification of data easier.
Each row have already unique mongo id field. I show id field on the table.
_Related ticket: #477

fix 477 - add id column to track tables

---

silo/tests/test.py
silo/tests/test_views.py
silo/views.py
tola/urls.py

Users can access silo_edit page via url event if they don't have a permission with that silo.
Check for Permissions added to silo_edit  view.
_Related ticket: #487

Fix #487 - Add permissions to silo edit page.

---

manage.py
silo/tests/test_views.py
tola/wsgi.py

The default encoding is `ASCII`, therefore we're having issues when converting/handling strings with special characters in the system. We need to use `UTF-8` instead.
- Set `UTF-8` as the default encoding when the system is initialized.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/269
https://stackoverflow.com/questions/31137552/unicodeencodeerror-ascii-codec-cant-encode-character-at-special-name#31137935

Fix special chars issue when handling strings

---

silo/forms.py
silo/tests/test_views.py
silo/views.py

**Purpose**
if users share their own tables with themselves or their organizations, they can see same table at the 'Tables shared with you section'
**Approach**
Edited query for shared_silos on silo list page.
**_Related ticket**: #486

fix #486 - prevent users to share table with themselves

---

silo/forms.py
silo/tests/test_forms.py
silo/tests/test_views.py
silo/views.py

In the "Shared" drop-down we need to filter the list of users to only users in one's Org.
- I had to update the Silo's form to filter the list of users
- I had to update the cleaning function as well, so it won't accept users from other orgs an so on.
Related ticket: #495

Filter list of shared users by Org

---

reports/tests.py
reports/urls.py
reports/views.py

Currently users can see all reports in their organization event if reports aren't shared with them. Prevent users from accessing reports which they haven't permissions 
New permissions added to reports list view.
_Related ticket: #500

Fix #500 - add permissions to reports list view

---

silo/tests/test_views.py
silo/views.py
templates2/display/merge-column-form-inner.html

When a user chooses to merge two tables and it fails, they should receive a notification. When a user chooses to merge two tables and it has success, they should be redirected to the silo detail page.
- I update the javascript to handle the JSON that the endpoint returns
- Update the do merge endpoint to return just JSON with the notification messages and the silo detail page URL and the merging has success.
Related ticket: #498

Add the merging tables notification and redirect

---

silo/forms.py
silo/tests/test.py
silo/tests/test_forms.py
silo/tests/test_views.py
silo/views.py
tola/activity_proxy.py

User wants to share their tables with their workflowlevel1s.
Workflow checks added to silo_edit, silo_detail and list_silo views.
_Related ticket: #465

Fix #465 - Make tables shareable with WFL1

---

silo/forms.py
silo/tests/test_forms.py
silo/tests/test_views.py

Other users (If they are not owner) can't change owner of the table.
Permissions checks added to silo form validation.
_Related ticket: #494

Fix #494 - add permissions to change owner functionality

---

silo/tests/test_views.py
silo/views.py

The user can 'view/edit' any public table, but the cannot make it private.
The user is only able to change a table to public or private if they are the owner.
Owner check added to toggle_silo_publicity view.
_Related ticket: #499

fix #499 - add permissions to changing publicity of table

---

templates2/display/silo.html
templates2/display/silos.html

Warning users to when they make table public, they are sharing table to anyone with Toladata account.
Confirmation message added to silo_list and silo_details page, in order to warn users about the process.
_Related ticket: #149

Fix #149 - Add warning to changing publicity of table

---

silo/forms.py
silo/tests/test_forms.py

When users want to change owner of the table, they want to see list of users from their organization.
Filter by organizations added to user list for owner selectbox
_Related ticket: #505

Fix #505 - filter users by org for owner selectbox

---

silo/api.py
silo/tests/test_customformview.py

When a user creates a form in Activity and publishes it, they would like the table created in Track to have a submission time for each entry.
- I appended the new column to the given ones
- I always add the time when a new data is sent to be saved
Related ticket: #481

Add timestamp column and value to custom forms

---

silo/api.py
silo/tests/test_customformview.py

When a user creates a form in Activity and publishes it, they would like the table created in Track to have a submission date for each entry.
- I appended the new column to the given ones
- I always add the date when a new data is sent to be saved
Related ticket: #480

Add date column and value to custom forms

---

silo/api.py
silo/tests/test_customformview.py

When a user creates a form in Activity and publishes it, they would like the table created in Track to have a submission by info for each entry.
- I appended the new column to the given ones
- I add the tola user's name when the tola user's uuid is sent to be saved
Related ticket: #482

Add submitted by info to custom forms

---

silo/api.py
silo/permissions.py
silo/tests/test_siloview.py

We should allow superusers to do whatever they want with silo's `data`, `get` and `list` endpoint (SiloViewSet) and don't check organization, programs and so on.
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/334

Fix #334 - Allow superusers to do anything in the SiloViewSet

---

silo/tests/test_siloview.py
silo/tests/test_views.py
silo/views.py

Merge function should merge based on assigned unique column. 
Merge function was using string as a keys, this issue prevented update rows on MongoDB and for each row was creating new row at the new merged table..
_Related ticket: #521

Fix #521 - make merge process based on assigned unique column

---

silo/gviews_v4.py
silo/tests/test_gviews_v4.py

Unique id fields not shown on Google spread sheets export of TolaTables.
Unique id field added to export process.
_Related ticket: #503

Fix #503 - add unique id field to google spreadsheets export

---

silo/gviews_v4.py
silo/tests/test_gviews_v4.py

Updating table from google spread sheet isn't working properly. When we set unique id column and try to update table, its generating new rows instead of updating existing rows. 
Code issue fixed. Control added to check integer unique fields. 
_Related ticket: #529

make update from google based on unique id

---

silo/api.py
silo/tests/test_views.py

Currently, when user tries to export private silo as JSON feed, we are warning to redirect them to API. However, we need more clear message with simple instruction.
Warning message was changed and user token added to message to inform users about how can they use API. 
_Related ticket: #530

Change warning message when users try to export private silo as JSON

---

templates2/500.html

Error message to direct users to support@toladata.com and not to tola.work
@Menda The template isn't used in any endpoint but they want to update it. :man_shrugging: 
Related ticket: #544

Update link of 500 error page to send email

---

silo/tests/test_views.py
templates2/display/silo.html

Hide the Make Private button of public silos (`/silo_details/`) for not owners.
Related ticket: #545

Hide the Make Private button in the Silo detail page

---

silo/tests/test_views.py
silo/views.py

After one user succesfully import data from onedrive, other users can not import data because User_social_auth table (which store tokens for onedrive access) has uid as a unique field and that is empty. Therefore, new users always get key conflict error. We need to fill that uid field with unique values.
UID field filled with generated UUID before it saved. So, each row will have its own unique value as a uid.
_Related ticket: #547

fill uid field of UserSocialAuth model
